import type{BeamCase,DistributedLoad}from'../types/beam';
import{formatNumber}from'../utils/units';
import{rotationDirection,signedNumber,verticalDirection}from'./diagramUtils';

const W=900,H=355,p=70,beamY=145;

export function LoadDiagram({beam}:{beam:BeamCase}){
 const sx=(x:number)=>p+x/beam.length*(W-2*p);
 const signed=(v:number)=>signedNumber(v,n=>formatNumber(n));
 const pin=(x:number,label:string)=><g key={`${label}-pin`}><path d={`M${sx(x)},${beamY+5} l-17,25 h34 z`} className="support"/><line x1={sx(x)-24} y1={beamY+33} x2={sx(x)+24} y2={beamY+33} className="support-line"/><SupportLabel x={sx(x)} y={beamY+53} name={label} kind="ピン" position={x}/></g>;
 const roller=(x:number,label:string)=><g key={`${label}-roller`}><path d={`M${sx(x)},${beamY+5} l-17,22 h34 z`} className="support"/><circle cx={sx(x)-9} cy={beamY+32} r="4" className="support-roller"/><circle cx={sx(x)+9} cy={beamY+32} r="4" className="support-roller"/><line x1={sx(x)-25} y1={beamY+39} x2={sx(x)+25} y2={beamY+39} className="support-line"/><SupportLabel x={sx(x)} y={beamY+58} name={label} kind="ローラー" position={x}/></g>;
 const fixed=(x:number,label:string)=><g key={`${label}-fixed`}><rect x={sx(x)+(x===0?-7:0)} y={beamY-44} width="7" height="88" className="support"/>{Array.from({length:9},(_,i)=><line key={i} x1={sx(x)+(x===0?-18:7)} y1={beamY-40+i*10} x2={sx(x)+(x===0?-7:18)} y2={beamY-47+i*10} className="support-line"/>)}<SupportLabel x={sx(x)} y={beamY+60} name={label} kind="固定" position={x}/></g>;
 const dimensions=beam.support==='simply-supported'?<><Dimension x1={0} x2={beam.supportA} y={260} sx={sx} label="左張出し"/><Dimension x1={beam.supportA} x2={beam.supportB} y={260} sx={sx} label="支点間"/><Dimension x1={beam.supportB} x2={beam.length} y={260} sx={sx} label="右張出し"/></>:null;
 return <section className="diagram-card"><div className="chart-title"><strong>荷重・支持模式図</strong><span>L = {formatNumber(beam.length)} mm</span></div><svg viewBox={`0 0 ${W} ${H}`}><defs><marker id="load-arrow" markerWidth="8" markerHeight="8" refX="4" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#d34b4b"/></marker><marker id="moment-arrow" markerWidth="8" markerHeight="8" refX="4" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#a044a0"/></marker><marker id="dimension-arrow" markerWidth="7" markerHeight="7" refX="3.5" refY="3.5" orient="auto-start-reverse"><path d="M7,0 L0,3.5 L7,7" fill="none" stroke="#557184" strokeWidth="1.4"/></marker></defs><rect x={p} y={beamY-5} width={W-2*p} height="10" rx="2" fill="#385a75"/>{beam.support==='simply-supported'&&<>{pin(beam.supportA,'支点A')}{roller(beam.supportB,'支点B')}</>}{beam.support==='cantilever'&&fixed(0,'左端')}{beam.support==='fixed-fixed'&&<>{fixed(0,'左端')}{fixed(beam.length,'右端')}</>}{beam.support==='propped-cantilever'&&<>{fixed(0,'左端')}{roller(beam.length,'右支点')}</>}{beam.loads.map(l=>{if(l.type==='point')return <PointArrow key={l.id} x={sx(l.position)} value={l.magnitude} label={`${l.id}: ${signed(l.magnitude)} N`}/>;if(l.type==='moment')return <MomentArrow key={l.id} x={sx(l.position)} value={l.magnitude} label={`${l.id}: ${signed(l.magnitude)} N·mm`}/>;return <DistributedArrows key={l.id} load={l} sx={sx} signed={signed}/>})}{dimensions}<Dimension x1={0} x2={beam.length} y={320} sx={sx} label="梁全長 L" always/><g className="sign-legend" transform="translate(75,18)"><rect width="320" height="25" rx="5"/><text x="10" y="17">鉛直荷重：＋ 上向き ／ − 下向き　　M：＋ 反時計回り</text></g></svg></section>;
}

function SupportLabel({x,y,name,kind,position}:{x:number;y:number;name:string;kind:string;position:number}){return <g className="support-label"><text x={x} y={y} textAnchor="middle">{name}（{kind}）</text><text x={x} y={y+18} textAnchor="middle">x = {formatNumber(position)} mm</text></g>}

function PointArrow({x,value,label}:{x:number;value:number;label:string}){const direction=verticalDirection(value),tip=direction==='up'?beamY+12:beamY-12,start=direction==='up'?beamY+62:55;if(direction==='zero')return <g><circle cx={x} cy={beamY-10} r="5" fill="#d34b4b"/><text x={x+7} y={beamY-16}>{label}</text></g>;return <g><line x1={x} y1={start} x2={x} y2={tip} stroke="#d34b4b" strokeWidth="3" markerEnd="url(#load-arrow)"/><text x={x+7} y={direction==='up'?beamY+72:48}>{label}</text></g>}

function MomentArrow({x,value,label}:{x:number;value:number;label:string}){const direction=rotationDirection(value);if(direction==='zero')return <g><circle cx={x} cy={beamY-25} r="6" fill="none" stroke="#a044a0" strokeWidth="3"/><text x={x+25} y={beamY-46}>{label}</text></g>;const path=direction==='counterclockwise'?`M${x+18},${beamY-12} A25,25 0 1,1 ${x-18},${beamY-12}`:`M${x-18},${beamY-12} A25,25 0 1,0 ${x+18},${beamY-12}`;return <g><path d={path} fill="none" stroke="#a044a0" strokeWidth="3" markerEnd="url(#moment-arrow)"/><text x={x+28} y={beamY-42}>{label}</text></g>}

function DistributedArrows({load,sx,signed}:{load:DistributedLoad;sx:(x:number)=>number;signed:(v:number)=>string}){const n=11,max=Math.max(Math.abs(load.startMagnitude),Math.abs(load.endMagnitude),1e-12);return <g><text x={(sx(load.start)+sx(load.end))/2} y="28" textAnchor="middle">{load.id}: {signed(load.startMagnitude)} → {signed(load.endMagnitude)} N/mm</text>{Array.from({length:n},(_,i)=>{const t=i/(n-1),x=load.start+t*(load.end-load.start),q=load.startMagnitude+t*(load.endMagnitude-load.startMagnitude),direction=verticalDirection(q),height=18+42*Math.abs(q)/max;if(direction==='zero')return <circle key={i} cx={sx(x)} cy={beamY-12} r="2.5" fill="#d34b4b"/>;const start=direction==='up'?beamY+height:beamY-12-height,tip=direction==='up'?beamY+12:beamY-12;return <line key={i} x1={sx(x)} y1={start} x2={sx(x)} y2={tip} stroke="#d34b4b" strokeWidth="2" markerEnd="url(#load-arrow)"/>})}</g>}

function Dimension({x1,x2,y,sx,label,always=false}:{x1:number;x2:number;y:number;sx:(x:number)=>number;label:string;always?:boolean}){if(!always&&Math.abs(x2-x1)<1e-9)return null;const a=sx(x1),b=sx(x2);return <g className="beam-dimension"><line x1={a} y1={y-9} x2={a} y2={y+8}/><line x1={b} y1={y-9} x2={b} y2={y+8}/><line x1={a+3} y1={y} x2={b-3} y2={y} markerStart="url(#dimension-arrow)" markerEnd="url(#dimension-arrow)"/><text x={(a+b)/2} y={y-7} textAnchor="middle">{label} {formatNumber(x2-x1)} mm</text></g>}