import type {BeamCase,BeamLoad,BeamResult,Reaction,ResultPoint} from '../types/beam';
import {sectionProperties,validateSection} from '../sections/properties';
import {solveLinear} from './linearAlgebra';

interface Unknown{kind:'force'|'moment'|'theta0'|'v0';position:number;label:string}
interface State{v:number[];theta:number[];moment:number[];shear:number[]}

function unknowns(c:BeamCase):Unknown[]{switch(c.support){case'cantilever':return[{kind:'force',position:0,label:'固定端反力'},{kind:'moment',position:0,label:'固定端モーメント'},{kind:'theta0',position:0,label:''},{kind:'v0',position:0,label:''}];case'fixed-fixed':return[{kind:'force',position:0,label:'左固定端反力'},{kind:'moment',position:0,label:'左固定端モーメント'},{kind:'force',position:c.length,label:'右固定端反力'},{kind:'moment',position:c.length,label:'右固定端モーメント'},{kind:'theta0',position:0,label:''},{kind:'v0',position:0,label:''}];case'propped-cantilever':return[{kind:'force',position:0,label:'固定端反力'},{kind:'moment',position:0,label:'固定端モーメント'},{kind:'force',position:c.length,label:'右支点反力'},{kind:'theta0',position:0,label:''},{kind:'v0',position:0,label:''}];default:return[{kind:'force',position:c.supportA,label:'左支点反力'},{kind:'force',position:c.supportB,label:'右支点反力'},{kind:'theta0',position:0,label:''},{kind:'v0',position:0,label:''}]}}

function grid(c:BeamCase):number[]{const xs=Array.from({length:c.divisions+1},(_,i)=>c.length*i/c.divisions);xs.push(c.supportA,c.supportB);for(const l of c.loads)if(l.type==='point'||l.type==='moment')xs.push(l.position);else xs.push(l.start,l.end);return[...new Set(xs.map(x=>+x.toFixed(10)))].sort((a,b)=>a-b)}

/** V=dM/dx. Upward forces are positive; applied counter-clockwise couples produce a negative M jump. */
function forceMomentAt(x:number,loads:BeamLoad[],reactions:{kind:'force'|'moment';position:number;value:number}[],side:'left'|'right'='right'):[number,number]{let V=0,M=0;const passed=(at:number)=>side==='right'?x>=at:x>at;for(const l of loads){if(l.type==='point'&&passed(l.position)){V+=l.magnitude;M+=l.magnitude*(x-l.position)}else if(l.type==='moment'&&passed(l.position))M-=l.magnitude;else if((l.type==='udl'||l.type==='linear')&&x>l.start){const t=Math.min(x,l.end)-l.start;if(t>0){const len=l.end-l.start,k=(l.endMagnitude-l.startMagnitude)/len,Q=l.startMagnitude*t+k*t*t/2,S=l.startMagnitude*(l.start*t+t*t/2)+k*(l.start*t*t/2+t*t*t/3);V+=Q;M+=x*Q-S}}}for(const r of reactions)if(passed(r.position)){if(r.kind==='force'){V+=r.value;M+=r.value*(x-r.position)}else M-=r.value}return[V,M]}

function state(c:BeamCase,xs:number[],u:Unknown[],values:number[],includeLoads:boolean):State{const loads=includeLoads?c.loads:[],rs=u.flatMap((q,i)=>q.kind==='force'||q.kind==='moment'?[{kind:q.kind,position:q.position,value:values[i]}]:[]);const theta0=u.reduce((s,q,i)=>s+(q.kind==='theta0'?values[i]:0),0),v0=u.reduce((s,q,i)=>s+(q.kind==='v0'?values[i]:0),0),moment:number[]=[],shear:number[]=[];for(const x of xs){const [V,M]=forceMomentAt(x,loads,rs);shear.push(V);moment.push(M)}const I=sectionProperties(c.section).inertia,EI=c.material.youngModulus*I,theta=[theta0],v=[v0];for(let i=1;i<xs.length;i++){const h=xs[i]-xs[i-1],k0=forceMomentAt(xs[i-1],loads,rs,'right')[1]/EI,k1=forceMomentAt(xs[i],loads,rs,'left')[1]/EI;theta.push(theta[i-1]+h*(k0+k1)/2);v.push(v[i-1]+h*theta[i-1]+h*h*(2*k0+k1)/6)}return{v,theta,moment,shear}}

function interp(xs:number[],ys:number[],x:number):number{let i=0;while(i<xs.length-2&&xs[i+1]<x)i++;const t=(x-xs[i])/(xs[i+1]-xs[i]||1);return ys[i]*(1-t)+ys[i+1]*t}
function equations(c:BeamCase,xs:number[],s:State):number[]{const endV=s.shear.at(-1)??0,endM=s.moment.at(-1)??0;switch(c.support){case'cantilever':return[endV,endM,s.theta[0],s.v[0]];case'fixed-fixed':return[endV,endM,s.theta[0],s.v[0],s.theta.at(-1)??0,s.v.at(-1)??0];case'propped-cantilever':return[endV,endM,s.theta[0],s.v[0],s.v.at(-1)??0];default:return[endV,endM,interp(xs,s.v,c.supportA),interp(xs,s.v,c.supportB)]}}

export function validateCase(c:BeamCase):string[]{const e=validateSection(c.section);if(!(c.length>0))e.push('梁長さ L は0より大きくしてください。');if(!(c.material.youngModulus>0))e.push('ヤング率 E は0より大きくしてください。');const pos=(x:number)=>x>=0&&x<=c.length;for(const l of c.loads){if(l.type==='point'||l.type==='moment'){if(!pos(l.position))e.push(`${l.id}: 荷重位置は梁の範囲内にしてください。`)}else if(!pos(l.start)||!pos(l.end)||l.start>=l.end)e.push(`${l.id}: 分布荷重の範囲が不正です。`)}if((c.support==='simply-supported'||c.support==='overhang')&&(!pos(c.supportA)||!pos(c.supportB)||c.supportA>=c.supportB))e.push('2つの支持位置を梁内で左から右の順に設定してください。');return e}

export function solveBeam(c:BeamCase):BeamResult{const errors=validateCase(c);if(errors.length)throw new Error(errors.join('\n'));const xs=grid(c),u=unknowns(c),zero=Array(u.length).fill(0),base=state(c,xs,u,zero,true),b=equations(c,xs,base).map(v=>-v),A=u.map((_,j)=>{const v=[...zero];v[j]=1;const col=equations(c,xs,state(c,xs,u,v,false));return col}).map((_,i,all)=>all.map(col=>col[i]));const values=solveLinear(A,b),s=state(c,xs,u,values,true),sp=sectionProperties(c.section),rs=u.flatMap((q,i)=>q.kind==='force'||q.kind==='moment'?[{kind:q.kind,position:q.position,value:values[i]}]:[]);const points:ResultPoint[]=xs.flatMap((x,i)=>{const sides:(['left','right'][number])[]=(c.loads.some(l=>(l.type==='point'||l.type==='moment')&&l.position===x)||rs.some(r=>r.position===x))?['left','right']:['right'];return sides.map(side=>{const[V,M]=forceMomentAt(x,c.loads,rs,side);return{x,shear:V,moment:M,stress:M/sp.modulus,rotation:s.theta[i],deflection:s.v[i]}})});const by=(key:keyof ResultPoint)=>points.reduce((a,p)=>Math.abs(Number(p[key]))>Math.abs(Number(a[key]))?p:a);const maxMoment=by('moment'),maxShear=by('shear'),maxStress=by('stress'),maxDeflection=by('deflection'),reactions:Reaction[]=u.flatMap((q,i)=>q.kind==='force'||q.kind==='moment'?[{position:q.position,force:q.kind==='force'?values[i]:0,moment:q.kind==='moment'?values[i]:0,label:q.label}]:[]);const allowable=c.deflectionLimit==='custom'?c.customDeflection:c.length/Number(c.deflectionLimit),safetyFactor=Math.abs(maxStress.stress)>1e-12?c.material.yieldStrength/Math.abs(maxStress.stress):Infinity;return{points,reactions,maxMoment,maxShear,maxStress,maxDeflection,safetyFactor,deflectionAllowable:allowable,deflectionOk:Math.abs(maxDeflection.deflection)<=allowable,equilibrium:{forceResidual:s.shear.at(-1)??0,momentResidual:s.moment.at(-1)??0},details:[`Euler–Bernoulli梁理論: EI·d²v/dx² = M(x)`,`E = ${c.material.youngModulus} MPa, I = ${sp.inertia} mm⁴`,`σ = M / Z, Z = ${sp.modulus} mm³`,`σmax = ${Math.abs(maxStress.stress)} MPa`,`安全率 = 降伏応力 / 最大曲げ応力 = ${safetyFactor}`]}}